/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#c6c6c6",
        "surface-container-high": "#2a2a2a",
        "surface-container": "#1f1f1f",
        "outline": "#988e90",
        "tertiary-container": "#000000",
        "surface-tint": "#00e628",
        "on-background": "#e2e2e2",
        "inverse-primary": "#006e0d",
        "tertiary-fixed-dim": "#c6c6c6",
        "inverse-on-surface": "#303030",
        "primary": "#00e628",
        "primary-fixed-dim": "#00e628",
        "primary-container": "#000000",
        "surface-dim": "#131313",
        "on-tertiary-fixed-variant": "#474747",
        "surface-container-low": "#1b1b1b",
        "on-secondary-fixed": "#410000",
        "surface-bright": "#393939",
        "on-tertiary-container": "#757575",
        "primary-fixed": "#75ff69",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#ffb4a8",
        "on-surface": "#e2e2e2",
        "on-error-container": "#ffdad6",
        "background": "#131313",
        "on-surface-variant": "#cfc4c5",
        "secondary": "#ffb4a8",
        "on-secondary": "#690100",
        "surface-container-highest": "#353535",
        "surface-variant": "#353535",
        "outline-variant": "#4c4546",
        "on-error": "#690005",
        "on-primary-container": "#008913",
        "on-tertiary": "#303030",
        "secondary-container": "#ff5540",
        "on-secondary-container": "#5c0000",
        "error": "#ffb4ab",
        "on-primary-fixed": "#002201",
        "tertiary-fixed": "#e2e2e2",
        "on-tertiary-fixed": "#1b1b1b",
        "on-primary": "#003a03",
        "on-primary-fixed-variant": "#005307",
        "secondary-fixed": "#ffdad4",
        "inverse-surface": "#e2e2e2",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed-variant": "#930100",
        "surface": "#131313",
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        'sans': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}